[package]
name = "ksana"
version = "0.0.1"
authors = ["Jitang Zheng <jitang.zheng@gmail.com>"]

[dependencies]
hyper = "*"
postgres = "*"
mysql = "*"
redis = "*"
rand = "*"
uuid = "*"
rustc-serialize = "*"
rust-crypto = "*"
docopt = "*"
