[package]
name = "ksana"
version = "0.0.1"
authors = ["Jitang Zheng <jitang.zheng@gmail.com>"]

[dependencies]
hyper = "0.6.14"
postgres = "0.10.0"
mysql = "0.20.1"
redis = "0.5.0"
rand = "0.3.11"
uuid = "0.1.17"
rustc-serialize = "0.3.16"
rust-crypto = "0.2.31"
docopt = "0.6.73"
