"log.list" = "SELECT id, user_id, message FROM logs WHERE OFFSET $1 LIMIT $2"
"log.add" = "INSERT INTO logs(user_id, type, message) VALUES($1, $2, $3)"
"log.list_by_user" = "SELECT id, type, message FROM logs WHERE user_id = $1 OFFSET $2 LIMIT $3"
